version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    allow:
    - dependency-type: "all"
    ignore:
    - dependency-name: "Moq"
    schedule:
      interval: "weekly"
    assignees :
      - "eduherminio"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees :
      - "eduherminio"
